### PR TITLE
Feature cloud setup

### PR DESCRIPTION
**Pull request by paranerd**

### CODE REVIEW

**Review by maxkimambo — CHANGES_REQUESTED** [review]
1: Not all the environment variables are being set, please double check 
e.g LOG_LEVEL='INFO' NODE_ENV PORT etc 

2: We should leave only the installation instructions in the README or have a separate install file no need for pre-commit instructions on the main README.

**Review by akushnarov — APPROVED** [review]

**Comment by paranerd** [comment]
Added `LOG_LEVEL`, `NODE_ENV` and `PORT`.
Left out `AGENTS_TOPIC_ID` because I think that one was meant for Pub/Sub?!
Also left out `DEMO_ENV_NAME` because it didn't sound very production-like - correct me if I'm wrong.

**Comment by paranerd** [comment]
As for the pre-commit info in README: I'm focusing on Cloud setup with this branch/PR trying to not mess with anything else, so I think this shouldn't be a merge-blocker.

**Review by maxkimambo — APPROVED** [review]
LGTM

**Pull request merged**
